In [1]:
import pandas as pd

In [2]:
s = pd.Series([10,20,30])

In [3]:
s

0    10
1    20
2    30
dtype: int64

In [16]:
d = pd.DataFrame({
    "name":["Ashish","Taksh","Harsh"],
    "Age":[20,19,21],
    "batch":["B","A","A"]})

In [17]:
d

     name  Age batch
0  Ashish   20     B
1   Taksh   19     A
2   Harsh   21     A

In [18]:
df = pd.read_csv("employee.csv")

In [19]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [20]:
df.groupby("Department")["Age"].mean()

Department
Human Resources           37.809524
Research & Development    37.042664
Sales                     36.542601
Name: Age, dtype: float64

In [23]:
df[df["BusinessTravel"]=="Travel_Rarely"]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
6,59,No,Travel_Rarely,1324,Research & Development,3,3,Medical,1,10,...,1,80,3,12,3,2,1,0,0,0
7,30,No,Travel_Rarely,1358,Research & Development,24,1,Life Sciences,1,11,...,2,80,1,1,2,3,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1462,39,No,Travel_Rarely,722,Sales,24,1,Marketing,1,2056,...,1,80,1,21,2,2,20,9,9,6
1464,26,No,Travel_Rarely,1167,Sales,5,3,Other,1,2060,...,4,80,0,5,2,3,4,2,0,0
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [29]:
df.groupby("Department").groups

{'Human Resources': [79, 100, 105, 112, 134, 139, 232, 310, 350, 422, 440, 453, 477, 493, 510, 535, 538, 551, 599, 613, 629, 633, 654, 655, 759, 789, 826, 835, 863, 878, 923, 943, 956, 962, 999, 1005, 1035, 1039, 1064, 1096, 1107, 1154, 1165, 1200, 1222, 1228, 1243, 1245, 1246, 1269, 1280, 1289, 1297, 1312, 1313, 1323, 1329, 1347, 1379, 1400, 1401, 1411, 1450], 'Research & Development': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 22, 23, 24, 25, 26, 28, 30, 31, 32, 34, 35, 38, 40, 41, 42, 44, 45, 47, 49, 50, 51, 53, 55, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 71, 72, 73, 74, 75, 77, 78, 80, 81, 83, 84, 85, 87, 88, 90, 93, 95, 99, 101, 102, 103, 104, 106, 108, 109, 110, 111, 113, 114, 116, 118, 120, 122, 123, 125, 126, 128, 129, 130, 135, 136, 140, 141, 142, 143, 145, ...], 'Sales': [0, 18, 21, 27, 29, 33, 36, 37, 39, 43, 46, 48, 52, 54, 56, 63, 70, 76, 82, 86, 89, 91, 92, 94, 96, 97, 98, 107, 115, 117, 119, 121, 124, 127, 131, 132, 133, 137, 138, 144, 151, 152, 154, 158, 159, 167, 168, 171, 174, 178, 182, 205, 210, 212, 215, 216, 218, 219, 223, 226, 227, 228, 233, 235, 237, 238, 241, 254, 261, 263, 265, 273, 277, 281, 282, 292, 293, 295, 297, 300, 301, 303, 306, 319, 320, 321, 327, 328, 331, 335, 338, 339, 343, 347, 349, 352, 354, 355, 357, 358, ...]}